apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-blitz-rave-com-tls
spec:
  secretName: k8s-blitz-rave-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: blitz-rave.com
  dnsNames:
    - blitz-rave.com
    - www.blitz-rave.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - blitz-rave.com
          - www.blitz-rave.com
